// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/budger-banner/Bodoni.tsx": () => import("../components/mockups/budger-banner/Bodoni.tsx"),
  "./components/mockups/budger-banner/Bricolage.tsx": () => import("../components/mockups/budger-banner/Bricolage.tsx"),
  "./components/mockups/budger-banner/Caslon.tsx": () => import("../components/mockups/budger-banner/Caslon.tsx"),
  "./components/mockups/budger-banner/Cormorant.tsx": () => import("../components/mockups/budger-banner/Cormorant.tsx"),
  "./components/mockups/budger-banner/DmSerif.tsx": () => import("../components/mockups/budger-banner/DmSerif.tsx"),
  "./components/mockups/budger-banner/Fraunces.tsx": () => import("../components/mockups/budger-banner/Fraunces.tsx"),
  "./components/mockups/budger-banner/Outfit.tsx": () => import("../components/mockups/budger-banner/Outfit.tsx"),
  "./components/mockups/budger-banner/Playfair.tsx": () => import("../components/mockups/budger-banner/Playfair.tsx"),
  "./components/mockups/budger-banner/SpaceGrotesk.tsx": () => import("../components/mockups/budger-banner/SpaceGrotesk.tsx"),
  "./components/mockups/budger-banner/Spectral.tsx": () => import("../components/mockups/budger-banner/Spectral.tsx"),
  "./components/mockups/budger-fonts/CartoonPremium.tsx": () => import("../components/mockups/budger-fonts/CartoonPremium.tsx"),
  "./components/mockups/budger-fonts/FontShowcase.tsx": () => import("../components/mockups/budger-fonts/FontShowcase.tsx"),
  "./components/mockups/budger-fonts/JuicyPicks.tsx": () => import("../components/mockups/budger-fonts/JuicyPicks.tsx")
};
