// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/budger-fonts/CartoonPremium.tsx": () => import("../components/mockups/budger-fonts/CartoonPremium.tsx"),
  "./components/mockups/budger-fonts/FontShowcase.tsx": () => import("../components/mockups/budger-fonts/FontShowcase.tsx"),
  "./components/mockups/budger-fonts/JuicyPicks.tsx": () => import("../components/mockups/budger-fonts/JuicyPicks.tsx")
};
